import React from 'react';
import style from './Music.module.css'

const Music = () => {
    return (
        <div className={style.music}>
            <h1>Music</h1>
            <div>Lorem ipsum dolor sit amet consectetur adipisicing elit. Error sint officiis adipisci dolorem nesciunt. Labore fuga magni laborum, molestias error, voluptas enim aliquam unde maiores necessitatibus reiciendis. Error, cupiditate quas.
                Odit, ratione! Laborum perferendis expedita commodi inventore quod alias laudantium aperiam porro incidunt id consequatur obcaecati officiis, iusto totam, nesciunt sapiente, beatae quas cumque quia aliquid labore sint. Magni, ipsa.
                Similique eius minima nesciunt a dolorem assumenda tempore reprehenderit, ab repellat cupiditate velit recusandae, mollitia praesentium iusto qui iure possimus ducimus expedita atque maiores exercitationem non fugiat quia blanditiis. Molestias?
                Reiciendis doloremque illum est nisi placeat voluptatem consequatur sapiente sequi. Voluptas quo dolores quas quibusdam cumque eos quae quod ex quos! Reiciendis illo, quas sed officiis nemo nulla quisquam quibusdam.
                Porro, nam? Neque repellendus quod sapiente, eligendi tempora aspernatur molestias? Eligendi facilis voluptatum repellat est possimus iure neque, praesentium officiis quae, minima pariatur dolorum labore, veritatis ullam omnis fugiat magni.
                Temporibus libero cumque tempora quod consectetur maiores repellat fuga, dolor corrupti. Mollitia, natus ex voluptatum vitae necessitatibus laborum iusto explicabo blanditiis vero distinctio odio officia obcaecati ratione totam animi consectetur?
                Vero illo nulla ullam impedit perferendis consequuntur accusantium nihil possimus, numquam officiis voluptates, eveniet tempore. Odit mollitia consequatur necessitatibus reiciendis tenetur laborum ipsam magnam porro corrupti! Aperiam ab quasi unde.
                Voluptatum sed fuga reprehenderit possimus! Quam deserunt cumque est non voluptates quidem aliquid, autem nobis. Veniam unde non doloribus aliquid iure praesentium, quo quia. Soluta magnam rem cupiditate ex quia?
                Ipsum quisquam vero at! Cumque eaque blanditiis nam sunt quos, soluta ex sapiente adipisci? Pariatur molestiae, dignissimos perspiciatis iste cupiditate mollitia aliquam quidem ducimus, ratione, quam veritatis optio vero porro.
                Ratione eveniet odio eius unde doloremque non cumque autem error temporibus iusto odit molestias laborum voluptate enim, atque nobis veniam incidunt. Laborum fuga ipsa recusandae omnis perferendis id, mollitia ad!
                Dignissimos temporibus fugit repellendus vitae hic laborum magni, illo ipsa esse, quasi facere nemo totam aut rerum officia eligendi neque autem tempora sapiente possimus itaque atque beatae velit? Rerum, rem.
                Aspernatur illo aliquid architecto maxime quasi qui! Iure sed earum eaque qui, nobis architecto possimus porro officia, corporis non odio harum minima cupiditate molestias illo maiores at quidem! Delectus, laudantium.
                Enim in nemo ratione facere, aliquam voluptatem consequatur! Illum id cumque tempora et optio unde dolorum ipsam nesciunt itaque distinctio, ea commodi culpa impedit, excepturi rerum placeat. Repellendus, minus facilis?
                Rem ea obcaecati quod exercitationem dicta labore officia? Autem pariatur consectetur sapiente fuga dolores dolor corporis debitis nulla eaque placeat magnam praesentium aspernatur aliquid, maiores dolore perferendis eius quis numquam?
                Dolorem voluptates dignissimos eveniet minus quo pariatur, nulla reprehenderit unde voluptatibus. Repellat et eius ipsa placeat? Ut sequi beatae nam ea nulla omnis enim quidem aperiam. Recusandae et cum beatae.
                Reprehenderit hic incidunt vel ducimus quasi voluptatibus iure rem laboriosam nam, aut id laborum officiis numquam nemo debitis modi voluptas eius culpa repellat fugit? Dolorum dolor fuga asperiores qui ea.
                Vel, sit commodi provident dolor cupiditate similique voluptates debitis tempora delectus dolores adipisci alias amet nulla nihil error voluptatem accusamus exercitationem, eum dicta numquam sapiente placeat odio magnam. Accusantium, expedita?
                Suscipit nisi sunt neque repudiandae minima quisquam quas, amet reiciendis cum, voluptatibus adipisci ducimus velit expedita provident! Qui hic dignissimos illum assumenda recusandae fuga eligendi exercitationem, consequatur nostrum! Expedita, reprehenderit!
                Minima id laudantium aperiam possimus necessitatibus quidem repellendus nisi aliquid maiores? Adipisci aliquam, provident dolore, officia quaerat cupiditate enim, sint libero at animi iste! Odit reprehenderit deleniti ullam consequuntur explicabo!
                Facilis nam molestias ducimus iure blanditiis itaque optio dicta, ea quas tempora error magnam reiciendis similique exercitationem atque amet laboriosam excepturi quia ipsum, fugit laborum soluta! Fugiat molestias error vitae.
                Fugit autem, ducimus vitae quidem iure veniam optio aspernatur quas numquam harum, laborum molestias ipsa maxime, explicabo voluptatibus repudiandae ipsam placeat provident consequuntur magni. Distinctio numquam officiis veritatis ipsum vero!
                Et provident explicabo veniam accusamus laudantium dicta cupiditate, vitae, dignissimos doloribus, eligendi quo. Ex totam aliquam velit nulla non temporibus labore voluptas illum vel quo, itaque exercitationem. Harum, suscipit saepe!
                Modi obcaecati odio voluptatum veritatis alias, excepturi culpa commodi error quidem cumque repellat a dolor, at nisi consequatur atque aspernatur! Ea, assumenda iusto! In id eius dolorem odit minus esse.
                Ducimus ullam fugiat quisquam, cum beatae tempore ipsa autem voluptate delectus laudantium. Suscipit, delectus laboriosam dolore nesciunt quidem eligendi dolor illum earum tempore laudantium quasi nemo commodi quam vitae soluta.
                Magni deleniti provident dolorem veniam consequuntur fugit nulla illo a expedita consectetur consequatur tempora architecto, sint sed reprehenderit ducimus possimus deserunt? Unde necessitatibus alias voluptates quaerat non commodi pariatur corporis.
                Explicabo ut molestias doloribus quos inventore similique a, ad ipsa iste magnam, earum commodi aspernatur tempora velit incidunt quidem! Dolorum dolor qui, iusto vitae sint deserunt maxime aliquam inventore nemo!
                Exercitationem excepturi at eligendi harum hic, deserunt ratione, assumenda dolorem delectus suscipit dolore quis rem repellendus asperiores esse est consequuntur impedit sapiente obcaecati magnam eaque dolorum ipsum itaque ullam? Pariatur.
                Commodi nobis quia itaque ipsa sunt mollitia minima vero nostrum animi maiores quod quasi earum possimus expedita alias, omnis officiis illo rem placeat exercitationem quis accusantium cumque quae dolores? Magni.
                Impedit eius omnis labore dolorem, sint sed amet optio ut exercitationem consequatur excepturi assumenda accusantium voluptas numquam accusamus officiis neque placeat ex qui veniam recusandae corporis odio distinctio? Magni, unde.
                Error unde aliquid iure, vero qui id eius. Officiis est doloremque suscipit repellat sapiente aliquam saepe soluta iusto, aspernatur corporis veniam consectetur itaque dolores corrupti laudantium eligendi eveniet odio vitae.
                Consectetur, nam blanditiis voluptatibus vero, consequuntur amet illum hic quibusdam temporibus vitae dicta nihil doloribus quos nobis modi dolorum laudantium nesciunt alias asperiores praesentium perspiciatis explicabo quidem, sunt esse! Provident!
                Laboriosam reiciendis commodi, necessitatibus a quaerat ab atque aperiam quis deserunt aspernatur numquam, odio voluptatum veritatis. Sit porro nostrum velit a itaque unde similique molestiae, id blanditiis optio cupiditate libero!
                Aliquid inventore, deleniti iure nam provident aliquam ducimus doloribus, numquam expedita dolore exercitationem sequi dignissimos unde velit animi minima molestiae ipsa? Fugit, asperiores. Accusantium dolor voluptatem excepturi neque unde similique.
                Nostrum laboriosam sed repellendus commodi eius a omnis minus, reiciendis dolorem corporis, in asperiores suscipit nisi cupiditate laborum corrupti esse, architecto accusamus deleniti cumque placeat ratione? Quam necessitatibus magnam perferendis.
                Quasi sit ipsa iusto commodi odio blanditiis vitae modi molestiae recusandae laborum amet dolorem dignissimos cum odit, fugit repellat, ex maiores tempora voluptatem pariatur veniam impedit officiis ea itaque. Quisquam.
                Distinctio consectetur unde voluptatibus numquam obcaecati laudantium iusto sint. Suscipit, molestiae architecto nulla delectus, dolorum incidunt quo quas nostrum et similique eius eum excepturi quae, dignissimos assumenda ut optio voluptatum!
                Ipsam illo vitae aspernatur, omnis hic consequatur amet fugit quibusdam eligendi dolor ab, esse laudantium minus enim. Repellendus cum reprehenderit dolor consectetur distinctio. Id quidem asperiores culpa dolorem molestiae. Ratione?
                Labore placeat fugiat quibusdam temporibus error rem facilis ipsa laboriosam quia nobis eveniet, nisi incidunt dolorem minima eaque repellendus! Velit quibusdam nam veniam assumenda sunt in quas quae quasi! Aut!
                Distinctio officiis delectus doloribus. Quibusdam ad nisi aut, officia quaerat reiciendis! Autem, culpa! Neque aliquid a, inventore corrupti praesentium sit alias libero aliquam voluptates nisi, laboriosam similique, optio officiis facilis?
                In, suscipit. Magni repellendus vitae doloribus excepturi ut sunt cupiditate dolores est quasi eligendi dolorum laborum repellat recusandae non aliquid similique ex deleniti itaque, ipsa cumque! Obcaecati saepe ea commodi!
                Mollitia impedit nesciunt itaque tenetur magnam repellat? Porro, ipsam dolorum vitae minima labore veniam debitis dicta possimus ab tempore dolores deleniti ullam laborum excepturi magni rem vel saepe perferendis nisi.
                Officiis libero, temporibus obcaecati placeat nulla necessitatibus. Quod aliquam quasi et corporis consectetur. Modi dicta quod facere. Dolore, ullam tempora eius saepe odio rem tenetur atque exercitationem expedita aliquid ea.
                Aliquam suscipit vero quaerat temporibus officiis ea. Fugiat ducimus in nihil laudantium amet at numquam, sint suscipit exercitationem, autem possimus alias ratione assumenda perferendis expedita aut? Aspernatur at temporibus odio.
                Rerum voluptatibus quam dignissimos pariatur! Mollitia, error eius incidunt in, rem earum ipsa, velit aperiam provident obcaecati nesciunt quisquam voluptates asperiores. Laudantium corrupti numquam deserunt incidunt voluptatibus sint dolorem assumenda?
                Amet assumenda itaque totam consequuntur ut. Illum dolores sunt voluptatum, veritatis nam iste architecto obcaecati deserunt quod ipsum quidem earum odio minus sed ea aspernatur laborum iure quisquam quos eos.
                Accusamus, odit. Vero quod repudiandae dolorem necessitatibus harum esse itaque, qui delectus. Odio eius adipisci molestias fugit voluptates perspiciatis consequatur impedit ea qui, assumenda, rem aliquid expedita ipsa deserunt animi.
                Provident quod doloremque nostrum quisquam cum ut ducimus cupiditate temporibus eligendi atque facilis officia repellat eos magni corrupti, fugit laudantium aperiam nobis non! Hic, ipsa odit? Odio quae eligendi rem.
                Eaque rem illum iure tenetur placeat voluptas sed ipsum et, nobis nulla. Molestiae repudiandae cumque, suscipit sequi provident fugiat odio, et tempore laudantium esse itaque consequatur molestias praesentium dolor nesciunt.
                Sunt libero mollitia repudiandae voluptatem tenetur sequi, officia in quod quis sit tempore dolorem nesciunt maxime debitis cumque, temporibus, repellendus itaque fuga optio corporis culpa ullam! Ex et sit maxime?
                At sit odit fuga doloremque aut, facere necessitatibus. Assumenda eaque aut ex quibusdam illo corporis, voluptates beatae neque, quam voluptatem numquam inventore ad harum nesciunt quaerat debitis cupiditate corrupti dolore?</div>
        </div>
    );
};

export default Music;