import React from 'react';
import style from './Settings.module.css'

const Settings = () => {
    return (
        <div className={style.settings}>
            <h1>Settings</h1>
            <div>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Eum reiciendis voluptates molestias distinctio sapiente quisquam corporis iure obcaecati similique earum cum, voluptatem totam explicabo vero minus, eos voluptate aut impedit.
                Omnis qui libero deserunt vitae consequatur nemo reiciendis sint pariatur amet, unde eligendi labore consectetur error id at perferendis deleniti maxime aliquid aspernatur ullam iste praesentium ex modi? Aspernatur, quia.
                Iure est consectetur, nulla sapiente doloribus id vitae explicabo quod, dolorem, quia placeat. Et alias repellendus unde. Ab consequuntur, est iure quasi, debitis tempore totam facilis quo ipsum sapiente consectetur?
                Laudantium dolorem, sunt in error vel inventore sequi voluptatem dolor nam iure dolores reiciendis iusto modi dignissimos facere adipisci magni animi saepe nobis tenetur. Eos nihil est voluptate nobis sit.
                Qui quae rem explicabo eos vitae nihil quasi, hic similique impedit provident itaque magnam cum iure, aliquam commodi tempore ullam laudantium illum. Sint rem repudiandae quisquam deserunt architecto cupiditate quos?
                Incidunt velit quod illo suscipit? Iure quisquam provident unde voluptate quibusdam natus cumque repellendus ipsam atque temporibus veritatis et itaque laborum similique vero exercitationem, laudantium adipisci fugiat, neque velit consequuntur.
                Minus mollitia labore quas neque vero ullam sit ex voluptate, accusantium blanditiis aut? Omnis alias fugiat doloribus corporis, ipsam cupiditate, dolores temporibus saepe, non minima nisi nostrum suscipit? Sint, expedita.
                Corporis in consectetur vero aperiam sit iure perspiciatis, voluptatum culpa saepe optio vel libero tenetur provident praesentium dolorum esse placeat fuga facere iusto, odit, fugit soluta? Autem fugiat hic officia.
                Quam deserunt quia ut earum est suscipit odit aperiam! Modi, atque. Dolores incidunt neque ex praesentium assumenda, unde rerum facere laborum asperiores itaque illum distinctio eveniet commodi quam, temporibus omnis?
                Nostrum iusto velit sapiente unde deleniti voluptatem quasi voluptatum! Mollitia laudantium repellat consequuntur praesentium alias voluptate maxime similique, enim sint illum quae voluptatum dolorem recusandae perferendis, iusto nesciunt. Similique, eveniet.
                Nihil, provident accusantium quos aliquam sit a magnam nulla. Natus ut, quis reprehenderit atque alias iure, impedit eaque error fugiat doloremque rerum perspiciatis porro dicta accusantium consectetur explicabo sed in!
                Non veniam omnis est obcaecati nemo, optio quod ipsum mollitia tenetur corrupti tempore. Accusantium natus sequi, doloremque facere impedit, totam porro aliquid maxime modi ullam optio nam, possimus tempore recusandae.
                Labore cum ab delectus! Tempora ratione dolorum ipsum adipisci fuga! Ut harum, debitis soluta sequi fuga quisquam necessitatibus nisi deserunt in deleniti ipsam, distinctio aspernatur facere fugiat provident. Neque, autem.
                Libero corporis sequi accusamus. Natus quas, iure maiores tempore blanditiis magni. Numquam labore veniam odio nemo voluptatibus, quidem temporibus quia repellendus unde ea, cumque deleniti voluptatum cum commodi, pariatur esse?
                Eligendi iure dolor minus laboriosam placeat similique neque earum repellendus magni cum, voluptatum, nisi praesentium! Mollitia provident, sint tenetur unde deserunt necessitatibus eaque fugit, nisi perspiciatis soluta debitis facere facilis?
                Eos hic voluptatum deserunt corporis reiciendis totam repellendus vel, non quaerat. Accusantium incidunt dolorum, et ex deserunt distinctio itaque consequuntur magnam. Iure natus incidunt ipsam mollitia similique maiores cum perspiciatis!
                Et facilis esse architecto ut nam enim dolor aliquid, culpa ea aspernatur, molestiae eos? Repudiandae, modi. Cum fuga officiis sint deserunt adipisci tenetur id, ducimus veniam quaerat corrupti aliquam magni!
                Atque, inventore non! Officia ipsam ipsa labore at nesciunt placeat dolor officiis, saepe quaerat ex velit rem laborum, corrupti quibusdam impedit voluptatum quas mollitia excepturi consectetur dolorum maiores cumque! Labore.
                Fugiat nihil quae vel tempore ratione labore at exercitationem omnis ab deserunt, eos culpa! Nulla qui amet, itaque expedita possimus aliquam! Quos, vitae tempore. Aperiam necessitatibus sint autem numquam blanditiis.
                Maxime maiores unde quo perferendis laborum voluptatibus aut dolorum similique odio facilis iure nisi veritatis quasi, libero recusandae obcaecati adipisci sunt praesentium voluptates itaque harum vel! Eaque reprehenderit laborum ipsum.
                Quas quasi officia repudiandae fuga, consequuntur, placeat veritatis tenetur temporibus quos, at hic aspernatur mollitia officiis. Odit est maxime unde quos, earum amet adipisci odio velit? Eum pariatur vel ipsam!
                Sint explicabo neque suscipit illum dignissimos quibusdam maxime dolorum. Provident autem incidunt, nobis eveniet est, accusantium velit at ad aperiam earum fugit voluptate molestiae qui aliquid itaque neque placeat corrupti.
                Ipsam molestiae nesciunt doloremque quod explicabo consequuntur rerum! Ex ullam magnam dicta repellat ipsa eum expedita cumque unde voluptatem tempora sequi reiciendis, quaerat fugiat architecto dolorem dolores doloremque eaque vero.
                Vero reiciendis modi, dignissimos dolores ullam veritatis corrupti ipsa ea consequuntur sequi distinctio aliquam laborum! Neque, quam, vel obcaecati natus, a officia magni facilis dolores esse ex illum eos impedit.
                Voluptas unde, aspernatur labore et dicta commodi explicabo. In perferendis laborum nesciunt saepe adipisci maiores, accusamus distinctio aut molestias reprehenderit eum, vitae placeat dolore voluptas magni! Sequi autem reprehenderit quia.
                Qui itaque inventore hic? Vitae corporis quia officia facilis fuga consectetur velit, et inventore. Adipisci perspiciatis reiciendis, nam, sapiente saepe eaque impedit itaque labore temporibus cumque possimus illum repellat minus!
                Corporis recusandae deserunt minima maiores id, consequatur laborum nostrum! Beatae molestias soluta debitis voluptatibus eligendi doloribus! Mollitia natus quisquam sint molestiae? Corporis deserunt odio libero expedita, alias fugit ut eum.
                Illum sapiente ipsam dignissimos iusto, eum nisi, dolores sequi sint ullam voluptates earum sit ut odit fugiat error nostrum debitis numquam corporis ducimus eius labore! Veniam aut fugit rem cumque!
                Asperiores quo laudantium, quae voluptatibus, laborum molestiae voluptas maiores inventore harum accusantium obcaecati nesciunt, quaerat aperiam officia numquam tempora non atque repellendus officiis ad porro? Maiores minima at corporis nam?
                Repellat, aperiam vero esse aliquid eaque incidunt vitae necessitatibus modi possimus aut nostrum culpa! Numquam beatae reprehenderit quae, nihil eius soluta ipsam a repellat minima sed esse ex pariatur quasi.
                Quo eos alias nihil officiis veritatis voluptatum suscipit voluptates aperiam exercitationem, sunt numquam ea tempora nisi ipsum libero odit quod aliquid similique? Rem veniam dicta sapiente non necessitatibus magni nulla?
                Numquam a libero dolores exercitationem incidunt non, ipsa vero debitis, reiciendis deserunt placeat saepe quisquam ex cumque ullam aut tempore neque modi nisi quam nihil quas animi. Animi, voluptas quibusdam.
                Quod fuga eaque ipsum neque odit reiciendis tempora ipsa nam repellendus consectetur fugit blanditiis delectus nihil hic ut pariatur, aperiam debitis assumenda perspiciatis. Esse obcaecati magni maiores distinctio, fugiat libero.
                Repellendus enim, voluptates temporibus eum debitis sequi, hic blanditiis excepturi nesciunt officiis earum eligendi quod cumque ducimus tenetur deleniti. Cupiditate deleniti quae officia quia voluptate. Similique deserunt voluptatibus quisquam autem!
                Tenetur eaque, sed laboriosam repellat accusamus fuga quibusdam aliquam maxime doloribus quos, nostrum, officia eligendi ratione molestiae ipsum itaque. Possimus nulla deleniti ad consequatur ipsam, explicabo ut cupiditate reprehenderit blanditiis.
                Beatae, pariatur debitis? Dolorum, quod pariatur obcaecati exercitationem itaque, fuga nemo, beatae quidem est sint incidunt consectetur. Aperiam, in, earum nostrum assumenda rem, fugiat odio similique nobis hic quasi deleniti?
                Amet repudiandae iusto cumque sunt a, laborum magnam deleniti dolore perspiciatis repellendus voluptatibus esse alias odit! Illo amet nostrum laboriosam, tenetur beatae voluptates maiores, quia accusantium nulla nisi quaerat eos.
                Laboriosam, iusto magni praesentium sunt animi esse neque cum maiores natus perspiciatis consequuntur quam minima ad totam tenetur nobis velit veniam odit excepturi iste officia est? Asperiores sint commodi eaque.
                Iusto sunt sed at quas cumque quaerat error nihil voluptates voluptatem. Fuga magnam, dolore sapiente reiciendis modi facere deserunt iste. Amet perferendis officia vel similique minima animi veritatis quasi inventore!
                Molestias nam id assumenda enim voluptate nostrum neque culpa non obcaecati soluta cupiditate minima eligendi quam, aut quo quidem voluptatum fugit praesentium animi iure quibusdam. Est repellat magnam nemo dolores.
                Cum eius doloremque repellendus asperiores temporibus incidunt magni similique quas doloribus alias, sit distinctio aut vero fuga nisi placeat ut quae unde earum optio perspiciatis tempora! Velit fugit aliquid obcaecati.
                Reiciendis molestiae tempora repellendus dolor culpa quibusdam sapiente animi nemo, illum, temporibus corrupti quae labore accusamus nihil consectetur esse distinctio obcaecati. Quasi, error doloribus nisi adipisci quos saepe dolorum suscipit.
                Sed impedit consequatur maiores unde amet libero, et ipsa adipisci a rem molestiae neque fugiat voluptatum ad placeat sit dolorum, modi iusto eligendi, minus blanditiis cupiditate. Explicabo, earum ipsam. Reiciendis.
                Amet facilis ea fuga rerum. Eos, aut illo nihil, expedita esse aspernatur nam architecto eius itaque perspiciatis pariatur, explicabo alias suscipit eligendi ex. Architecto sunt, amet maxime optio nostrum sed.
                Nostrum fuga unde vel nisi nihil atque pariatur harum voluptatum illo, blanditiis sint explicabo est saepe error rem adipisci officiis, consectetur dolore necessitatibus qui vero, voluptas assumenda. Unde, obcaecati quas?
                Consequuntur laudantium voluptatibus cum facilis corrupti blanditiis ducimus expedita quia. Illum aspernatur ad iste molestiae architecto hic ipsa, blanditiis earum exercitationem possimus enim nemo? Quod itaque veniam id iure corrupti.
                Velit ullam dolor ipsum soluta modi animi reprehenderit illum quidem aspernatur. Ipsam aspernatur voluptates excepturi rem eligendi atque inventore. Nam facere commodi accusantium provident reprehenderit dolor ipsa recusandae tenetur excepturi.
                Exercitationem quae rerum accusantium! Dolorem, sit illum ea sed illo architecto animi provident? Necessitatibus et ratione doloremque harum. Saepe ad inventore, fugiat minima molestias vel mollitia necessitatibus vero quos corrupti.
                Atque itaque possimus magnam, pariatur quod dolore soluta qui! Optio deserunt dicta sapiente maxime corrupti quidem laborum voluptate hic, perspiciatis iste aperiam modi odit voluptatibus dignissimos atque delectus, inventore debitis?
                Cupiditate sint optio quo recusandae molestias dicta, amet quam quia eius delectus quos? Dignissimos ducimus quasi odio dolores exercitationem tempora harum! Porro nam quo tempora, assumenda veniam laboriosam quae quasi.</div>
        </div>
    );
};

export default Settings;