import React from 'react';
import style from './News.module.css'

const News = () => {
    return (
        <div className={style.news}>
            <h1>News</h1>
            <div>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Nam minus, aliquid vel eaque consequuntur, temporibus facere excepturi rerum similique, culpa quo? Possimus maxime ut mollitia laboriosam voluptatum nulla beatae maiores.
                Voluptatem sit odit nisi laboriosam placeat quos distinctio fuga debitis facere accusamus odio consequuntur ex nobis harum nam unde, rem ipsum repellendus ratione modi dolorem amet nihil! Eveniet, neque voluptates!
                Provident consequatur eum dicta vero? Ipsam, rem ut dignissimos possimus officiis qui dolorem at in assumenda aliquid deserunt corrupti voluptate excepturi iusto voluptatibus, itaque perspiciatis et aliquam ipsa repellat! Minima.
                Libero facilis, tempore exercitationem excepturi similique enim in, quod harum dolorum sed dicta sequi, natus illo nulla quae consequuntur inventore dolore possimus suscipit sit reprehenderit? Ea, ad cupiditate! Molestiae, rerum!
                Esse error quasi ea sed atque molestiae recusandae dignissimos nobis eligendi, quas numquam eius aliquid perspiciatis quaerat doloremque a odit dolore est eaque aperiam nam. Temporibus voluptatem laudantium laboriosam optio!
                Magnam fugiat corrupti dolore ea similique recusandae molestias nam quisquam autem voluptas! Velit neque ipsa deserunt, officia ducimus corporis veniam, repellat ut voluptate veritatis nihil dolorem illo. Nisi, doloremque at!
                Cupiditate excepturi explicabo cumque nesciunt fugiat ipsa ea. Facere eius vitae earum dolorum sequi, voluptas blanditiis labore, doloremque accusamus eum iste enim ea perspiciatis in ad. Veniam a cumque quas.
                Explicabo illo incidunt, in perferendis nihil debitis reiciendis mollitia aspernatur quas placeat eius distinctio! Eveniet magni, error mollitia temporibus eos quaerat deleniti ipsam laboriosam ab asperiores architecto fugiat fuga ut!
                Id, in minima non blanditiis enim beatae eligendi commodi facere numquam quas expedita facilis, a saepe delectus nemo cumque aperiam aliquid? Quod qui quia commodi laboriosam? Iste numquam veniam facere?
                Minus fugit molestiae aliquam! Repellendus porro possimus et, odio temporibus perferendis officia maiores enim id ad ut ratione magnam blanditiis, inventore adipisci rem! Assumenda necessitatibus eum itaque pariatur facere quaerat.
                Officiis laborum nobis consectetur a aliquam vitae, ipsum ratione repellendus aspernatur voluptates dolorem doloremque, consequatur molestias totam corrupti perferendis incidunt asperiores voluptas. Ab, fugit ipsum. Expedita perferendis distinctio ducimus aspernatur.
                Animi atque consectetur, accusamus et neque quos minima ratione, dolor ipsum est ad possimus quisquam, eos magni velit. Quam soluta quod a fugiat dolorum corrupti blanditiis sed quaerat omnis officia?
                Omnis accusamus sunt eius repellendus cupiditate non distinctio mollitia laboriosam error animi inventore aut autem molestiae velit, vero soluta facilis porro ratione at dolorem sapiente debitis, nesciunt odit? Dolorem, culpa.
                Beatae, quibusdam. Porro dolores nam vitae, necessitatibus natus incidunt quam quod veritatis. Voluptatibus maxime harum sapiente libero ipsum ducimus eius modi quod earum qui numquam expedita vel, excepturi eos molestiae?
                Cupiditate officiis illum voluptate eius ex quam minima unde reiciendis quo quae repellat, doloremque voluptatum! Sit id, itaque ipsa ipsum reiciendis, numquam suscipit illum omnis deleniti, possimus natus consequuntur expedita!
                Architecto ratione aliquid tenetur soluta! Sed temporibus nemo nam nisi, sapiente molestias dolorum inventore tenetur consequuntur necessitatibus dolorem laboriosam doloribus, officiis totam voluptatem aliquam, minus fugiat id distinctio dolor libero!
                Harum, accusamus minus ab distinctio quis asperiores qui dicta fuga omnis. Eum, deserunt deleniti. Rem quia dolores, aliquid debitis impedit esse ducimus ullam ipsum temporibus. Minima debitis vel enim ducimus.
                Labore accusamus alias tempora modi, explicabo id et illo vel delectus maxime! Adipisci ducimus voluptatum nulla provident eius in, nesciunt reiciendis quos, ad nostrum iure inventore magni delectus ipsum animi.
                Odit, rerum molestias. Architecto maxime, exercitationem, accusamus corrupti aliquam eius consequatur voluptatum tenetur quisquam odio vel pariatur eos adipisci incidunt itaque qui expedita similique? Delectus beatae exercitationem culpa animi vitae.
                Ipsum quisquam ea eligendi iste laboriosam explicabo molestias, error ullam natus voluptas ad excepturi veniam aliquam magni quae repudiandae corporis. Placeat nulla fuga distinctio. Qui reprehenderit sint hic id provident.
                Quaerat blanditiis, praesentium omnis suscipit voluptatem placeat, error, explicabo earum animi accusantium expedita vel reiciendis. Optio cupiditate nihil perspiciatis explicabo possimus voluptate fugit, ratione soluta minus blanditiis sit deleniti iusto?
                Quae obcaecati similique eaque illo asperiores voluptates architecto nisi ullam provident corrupti necessitatibus voluptatem deleniti fugit minima doloribus, minus molestias ducimus adipisci. Excepturi labore itaque, quod impedit assumenda tempore natus?
                Repellendus accusamus nam iure labore totam esse quia ab rem sapiente maiores iste, magni corrupti. Cumque in accusantium delectus, odit corporis et a necessitatibus ab repellendus tempore rerum repellat consequuntur.
                Alias nisi ipsa provident quae placeat eius quidem cum, quam itaque at molestias deleniti culpa quibusdam inventore consectetur, fuga quas nostrum dignissimos? Minima ad deserunt hic eius at, placeat sit.
                Consectetur cumque neque distinctio assumenda eveniet totam eius, dolorem illum. Saepe ratione dicta nihil cum corporis harum possimus natus blanditiis, nulla eos rerum debitis obcaecati maiores optio repellat alias earum?
                Suscipit, saepe aspernatur. Unde ut magnam repellendus perferendis earum voluptatum minus hic. Labore repellendus quis assumenda facere ullam, dolore in porro. Modi sunt nemo perferendis commodi odit quasi. Quam, velit?
                Alias harum cum nam aut? Neque maiores illo at ipsam doloremque magnam, beatae, officiis earum blanditiis, explicabo culpa ipsum rem harum debitis unde veritatis delectus! Tempora recusandae tempore blanditiis ex?
                Quod ducimus deleniti deserunt modi perferendis laudantium? Non aut iste praesentium voluptate? In officia architecto aliquam et dolore illum fuga, totam labore animi, molestiae recusandae reprehenderit sequi, vitae repudiandae aspernatur.
                Quisquam temporibus quo possimus nihil minima soluta, aperiam dolor provident! Veniam inventore nulla enim quod praesentium dolore maiores voluptate tempora quasi vitae hic aliquid commodi, harum, voluptatibus expedita voluptatem at?
                Repudiandae veniam cupiditate esse necessitatibus labore fugiat eveniet eaque dolorum temporibus accusamus quod odio repellat pariatur quisquam sed, maiores quis nobis voluptatibus iusto deleniti ipsum explicabo? Libero non ex facilis!
                Non ab nisi, esse reiciendis ut distinctio illum odio corporis praesentium iure minima! Nobis nesciunt deleniti nam quod quis beatae quam quisquam cum facere et iusto voluptates mollitia, dolores culpa?
                Perferendis nihil facere modi sequi repudiandae, ex quasi error et quam sint reiciendis, excepturi voluptas tempora veniam. Deserunt rem aspernatur quas, eum corporis dolorem molestiae, quibusdam distinctio ab voluptas explicabo!
                Unde, ad. Natus expedita eligendi pariatur dolor magni maiores, nulla consequuntur unde veniam dolorum molestiae itaque saepe beatae ipsa voluptas molestias nesciunt ipsum error qui. Alias quia aut a porro!
                Eligendi, in! Provident, quasi consequuntur, consequatur nulla recusandae est ea ipsum, accusantium quo optio temporibus saepe quibusdam dolore nobis animi deserunt! Fugit eveniet facere explicabo a esse sapiente vitae sunt?
                Recusandae, quas! Non, temporibus itaque pariatur, eligendi reprehenderit perferendis quia nulla nobis sint architecto ut ipsam facilis accusamus odit voluptates fugiat, minima dolore inventore aperiam atque vero doloremque suscipit beatae.
                Eligendi doloribus voluptas reprehenderit quaerat aut! Officiis consequatur maiores architecto explicabo voluptatibus voluptates facere, vitae cumque praesentium magnam. Animi accusamus odio mollitia ipsam. Labore ullam quis sapiente excepturi harum aliquam.
                Repellendus, in! Aspernatur debitis doloribus quo dolorem assumenda cumque laudantium deleniti ipsum rem, eaque similique expedita doloremque quam nisi quaerat vero. Aspernatur sapiente quibusdam hic, facilis atque ea amet libero.
                Ut excepturi magnam illo provident tempora voluptatibus debitis architecto consectetur, adipisci quibusdam quaerat nisi molestiae, enim reprehenderit, ipsam tenetur eius iure maiores officia quod quas maxime doloribus. Quaerat, ullam voluptatibus.
                Nihil labore, est distinctio rem, repudiandae in saepe quasi, earum ea eveniet nesciunt maiores veniam delectus. Nihil illum, cupiditate quos fugit vitae ad ratione debitis reiciendis, et illo, repellendus dignissimos?
                Temporibus alias fugit asperiores sapiente quo expedita officia earum, odit deleniti nihil praesentium. Ex ut nemo praesentium iste dicta porro maiores eum nostrum magnam! Deserunt distinctio dolorum autem sequi soluta.
                Repellendus necessitatibus cupiditate magnam quas suscipit voluptatem non tempora totam explicabo. Laboriosam sit enim quod, esse pariatur nostrum quibusdam alias eaque cum, quae dolor cupiditate fugit quos ullam doloribus? Autem!
                Est voluptatibus consectetur sunt voluptatem non assumenda. Sit odio vero voluptate nulla hic sint labore, cum sed quia doloribus eaque at molestiae, animi fuga similique quis rem a repellat eius.
                A ab aspernatur expedita. Labore deserunt, quaerat debitis blanditiis dolorum eligendi cum voluptatibus mollitia iusto quis dignissimos modi, assumenda illo repellendus ad. Laboriosam nostrum quo eius animi, labore neque culpa?
                Perspiciatis enim aliquam labore dicta? Repellat facere, quia quaerat dignissimos amet tempore delectus eligendi facilis, adipisci pariatur distinctio culpa, explicabo obcaecati quasi id molestiae incidunt porro nulla labore ipsum fugiat?
                Perspiciatis mollitia commodi quos quisquam pariatur laudantium eius, assumenda vero quis ea magnam nemo quod suscipit qui voluptatum vitae facilis saepe, culpa impedit dolorum asperiores modi ab, accusamus aperiam! Expedita.
                Voluptatum, eum incidunt inventore officia facere atque corrupti aliquam, repellendus, consequatur quia eius cumque suscipit sequi voluptates odit labore nihil. Facilis nostrum, in neque accusamus fuga dolorum. Rem, vero expedita.
                Similique cumque dignissimos non voluptatibus at, suscipit autem laboriosam quis, rerum provident nostrum officiis laudantium eligendi commodi inventore aliquid beatae deleniti odit neque. Vero molestiae exercitationem autem, nemo possimus praesentium?
                Laudantium dolores provident quas sunt dolor assumenda ea officiis delectus, eaque, explicabo ducimus repudiandae quisquam similique sapiente consectetur, tenetur aut! Voluptate repudiandae aut quos architecto magnam. Nobis provident tempora deleniti?
                Quam, quae est. Accusamus similique fugiat dolore eaque sunt odio voluptatem iure voluptatibus repellendus at aliquam quam optio quas consequatur vel, eveniet qui quaerat facilis illum porro commodi quasi consectetur.
                Iste quia autem natus accusamus sit, repellat deleniti inventore maxime totam unde adipisci dolore doloremque ullam architecto atque doloribus ipsam impedit, corporis quidem accusantium! Voluptas, optio? Quisquam fugit voluptatem aliquid!
                Ducimus, dicta? Praesentium reiciendis porro deleniti non iste modi in obcaecati accusantium ea inventore! Minus quia inventore iste quae, explicabo sed, tenetur reiciendis mollitia ipsa illo minima itaque corrupti atque?
                Incidunt est harum, labore at nesciunt quibusdam sit fuga sequi excepturi et quos quidem amet libero voluptates corporis! Blanditiis quam eligendi excepturi optio amet fuga libero voluptates itaque sit est.
                Necessitatibus quod perspiciatis qui natus perferendis nihil, quam quo cupiditate molestiae blanditiis quisquam sapiente neque beatae porro optio nisi iste modi atque ut dolorem. A rerum mollitia totam consectetur temporibus.
                Ullam provident delectus aliquam corrupti rem amet saepe unde atque sapiente, explicabo dicta voluptas maxime fugiat natus esse repudiandae illum. Sequi consequatur quis voluptates iusto debitis temporibus, accusantium quod ducimus.
                Commodi facilis obcaecati officia perferendis, quod tenetur repellat at dignissimos ratione qui expedita labore saepe hic magni, pariatur tempora blanditiis corrupti aliquid. Harum tenetur sequi, aliquam quaerat molestias ex facilis!
                Ipsam ullam exercitationem expedita est sapiente illo aperiam praesentium officia. Dicta beatae quae facere accusantium sed. Optio, odio molestias. Vel illo, quo magni enim esse quam reiciendis pariatur repellat inventore!
                Quam numquam quidem adipisci odit ex totam delectus natus, a rem ipsa at saepe commodi soluta neque sit in. Placeat recusandae quam est sit aliquid voluptatibus voluptate autem deserunt expedita!
                Optio quibusdam molestiae beatae culpa minima labore nostrum magni molestias ad vero, mollitia voluptatem soluta quam. Ipsa sint vitae et hic temporibus rem vel ipsam odio. Accusamus unde totam molestias.
                Reiciendis, deleniti, repellendus sequi totam iste fugit ea expedita modi incidunt atque officiis placeat magni itaque, voluptatem pariatur possimus fugiat? Perspiciatis maiores nisi quidem mollitia tempora fuga ex magnam error!
                Perspiciatis reprehenderit, pariatur cupiditate porro, assumenda voluptatibus eos explicabo, aperiam aliquid sed consequuntur! Veritatis laboriosam vitae molestiae, inventore reprehenderit, nihil expedita officiis possimus numquam consequatur libero temporibus minima voluptates minus.
                Impedit voluptate, architecto quaerat eligendi quia aperiam soluta hic tempore facere. Delectus, tempore cum, maxime, obcaecati quis veritatis dicta adipisci libero similique incidunt temporibus unde illo minus numquam tempora impedit!
                Enim corporis repudiandae nemo, est voluptatibus at esse eius! Sapiente molestias nobis est culpa illo nulla similique voluptate molestiae ducimus cumque mollitia commodi fugit minima provident ullam, inventore asperiores id.
                Ipsa molestiae harum, quo ipsam magnam eveniet illum? Quos atque rerum ut at minus dolorem enim aperiam consequatur dolorum reiciendis, nam est nesciunt eum nulla molestiae unde facilis excepturi quis.
                Ut quaerat magni placeat molestias soluta, dignissimos recusandae exercitationem odio. Quas consequuntur laudantium, repellendus modi eligendi quia fuga dolor magni, aspernatur, quidem necessitatibus aliquam autem numquam quos! Assumenda, repellat voluptas!
                Qui, nulla omnis doloribus tenetur facilis adipisci sed assumenda enim ipsum cumque, debitis corporis dolorem amet? Vel ex officiis fugit quibusdam exercitationem, omnis excepturi vitae mollitia aspernatur placeat ea consequatur.
                Corrupti quo, neque sunt magni, culpa nesciunt obcaecati repellendus sapiente eos illum excepturi iusto quaerat esse voluptate. Accusamus quisquam ullam soluta rerum sed officiis debitis, ab labore minima iure assumenda!
                Quidem, repellat corrupti dicta, optio consequuntur praesentium dolores quisquam architecto odio repudiandae omnis corporis blanditiis tempora earum neque sit possimus soluta! At velit incidunt quos laboriosam dolore id magnam porro.
                Soluta illo numquam et obcaecati tempore aliquam, beatae a cupiditate deserunt praesentium laborum similique culpa nihil in reiciendis provident voluptate, asperiores cum laboriosam tenetur dignissimos aut nesciunt? Deleniti, minus minima.
                Aliquid in voluptates fugit esse? Laborum eius deleniti atque, dolorem quibusdam similique! Ex enim eos placeat quasi iure reprehenderit, fuga ea commodi? Accusamus illum nobis quia dicta. In, fuga facilis?
                Aliquid excepturi accusamus, magnam libero laboriosam ipsam laborum obcaecati impedit laudantium alias dolore cumque officiis quod unde inventore exercitationem adipisci enim corrupti deserunt voluptatibus necessitatibus vitae tempore, pariatur porro. Quae.
                Sequi molestiae saepe, eos eveniet nostrum quisquam illum, reprehenderit amet est odio eligendi magnam sint optio facere dolores explicabo qui tempore inventore fuga accusantium aliquid enim ea! Molestias, facilis ratione?
                Ipsum rem temporibus, incidunt cupiditate aspernatur facilis veniam quos facere repellendus non similique tempora quidem sapiente sunt architecto ipsam eos dolor illum corporis modi vel laudantium vero? Officiis, modi sint.
                Mollitia nemo unde magnam dolores aut dolorem. Voluptatibus magni voluptatum, qui perferendis repellendus quibusdam ea illum sed ullam accusantium veniam ipsum adipisci alias nesciunt tenetur saepe, dolor quo enim vel.
                Voluptatibus eveniet ipsum quod reiciendis hic impedit fugiat officiis numquam placeat optio porro autem, doloribus aliquam, quae eligendi perspiciatis accusamus! Similique repellendus reprehenderit commodi perspiciatis! Iste at voluptas ipsa pariatur!
                Impedit at iste quo similique quidem ipsum atque voluptas inventore natus in. Quod dolorum architecto expedita labore! Illum, ab omnis magnam explicabo repellendus error accusamus quos veniam quo, culpa dolorem.
                Dolorum natus illum doloribus unde asperiores omnis repudiandae veniam est error delectus temporibus itaque eos iure eum quibusdam fuga nesciunt perspiciatis, nisi pariatur nulla quas. Animi excepturi eum earum numquam?
                Quae consectetur, eveniet cumque temporibus rerum voluptates natus excepturi alias corrupti ab magni deleniti quas tempora ratione deserunt vel assumenda fugit? Ipsam magnam cupiditate et veritatis tenetur, ipsum error voluptates.
                Facilis aliquid maxime omnis nam voluptatibus aspernatur dolores inventore autem quis reiciendis, molestias fugit cupiditate, sequi, laborum facere qui hic quam. Qui dolores exercitationem fuga excepturi, consectetur sapiente culpa doloremque.
                Hic enim deleniti, nihil illum deserunt alias, facilis est odit ipsa voluptatum, similique placeat eligendi consectetur inventore autem quas! Ipsam, sunt doloribus tempora nisi inventore excepturi nesciunt dolore beatae iusto?
                Vitae ipsam ad architecto earum unde esse praesentium sapiente sint consectetur minima, sed aliquid aperiam eos quasi reprehenderit animi ullam? Sint veritatis, tenetur excepturi asperiores aut consequatur? Mollitia, qui minima.
                Inventore ea tempora minus esse itaque corporis. Itaque fugit optio nesciunt a facere quisquam ullam nobis impedit voluptas incidunt animi dolor, architecto excepturi minus aliquam ea id eligendi placeat. Magnam.
                Maxime modi illum magnam, ipsam molestias aperiam eius, obcaecati voluptas, odio facilis perferendis neque aut dolorum ipsa exercitationem laudantium accusantium at autem eligendi repellendus numquam sed debitis rerum iusto? Aliquam!
                Quibusdam vitae quod voluptate libero quasi dolor praesentium porro quos sapiente sed, voluptatum non odio placeat nostrum accusamus provident molestias natus nesciunt rerum corrupti adipisci exercitationem cum! Labore, debitis odit.
                Esse praesentium commodi, neque nihil asperiores fugit atque repellendus eaque, nam nostrum itaque assumenda perferendis deserunt necessitatibus aut! Omnis id quia at soluta iusto animi quisquam magnam, voluptatum nulla provident?
                Incidunt reiciendis ut architecto placeat quasi aspernatur cum, possimus asperiores earum, facere modi? Deleniti, libero voluptas earum natus temporibus maxime harum at necessitatibus, corrupti distinctio aliquam commodi error animi ullam.
                Eligendi reprehenderit minima, harum error voluptates, sunt unde necessitatibus veniam ipsam quas nesciunt voluptatibus esse consectetur at. Mollitia at minima consectetur blanditiis debitis laboriosam ipsum quos, temporibus, iusto laudantium necessitatibus.
                Quod nesciunt soluta et maxime, nisi animi, dignissimos consectetur cumque aut quidem, dolores autem incidunt reiciendis dicta atque ipsam inventore tempore. Illum soluta delectus laudantium. Aut alias vero accusamus at!
                Adipisci itaque, dolores ex totam illum non quis id vel a quod aliquid consequatur eum, perferendis doloremque? Magnam repellendus, vitae explicabo quasi illum, sequi eum numquam sed aperiam, autem aspernatur.
                Maxime eum possimus, nemo facere iure sint odio, non quo rem adipisci excepturi ea voluptatem quod alias sunt vero aperiam aliquam? Corrupti delectus fuga molestiae, modi libero similique odio recusandae?
                Dolor quidem saepe numquam fugit eligendi iusto dolores asperiores doloribus molestias, fuga labore eos soluta quas quod mollitia perferendis iste eaque excepturi veniam explicabo sapiente corporis totam neque similique? Sit.
                Quisquam labore deserunt optio dignissimos, in harum accusantium ipsum tenetur ullam fugiat veritatis earum quos. Eius obcaecati quis beatae, at odit, quod ea unde, impedit nobis pariatur dignissimos corrupti accusantium?
                Quae ratione rem officiis dignissimos voluptates voluptate, fugit laboriosam possimus recusandae ipsa qui placeat deleniti dolor repellendus, illum quasi repudiandae hic doloremque ex libero est explicabo modi facilis. Veniam, temporibus!
                Accusantium doloribus, enim, earum dignissimos dolorum voluptatum qui harum impedit repudiandae doloremque fugiat maxime consequatur provident dolores asperiores. Commodi dolore sequi obcaecati illum eveniet quibusdam possimus nobis, amet reiciendis ducimus.
                Distinctio, consequatur inventore. Iste doloribus laboriosam ipsa nam voluptas, doloremque nesciunt ea perferendis delectus, facere assumenda saepe commodi? Tenetur, ut illum quam eum consectetur laudantium modi voluptatem error non beatae!
                Fuga reprehenderit dignissimos quaerat blanditiis rem corporis sit voluptatem ipsum quia! Ducimus, odio voluptatem! Corporis dignissimos, debitis ratione reiciendis veniam amet ducimus nemo facere fugiat inventore id earum beatae ad?
                Sed neque optio corrupti, veritatis labore voluptate similique voluptatibus recusandae ullam quis fugit doloremque eligendi laboriosam a? Rerum id pariatur sit doloribus nemo illo nobis aliquid, animi sint doloremque ab!
                Ea excepturi tempore maxime sint animi, maiores numquam ut. Dolore unde doloribus corrupti rerum, quis impedit beatae labore sunt, cum eveniet placeat. Corrupti dignissimos suscipit exercitationem, ipsa nihil temporibus odit?
                Asperiores molestias explicabo, ratione unde tempore laboriosam itaque distinctio accusamus aut fugit, quisquam iste ex libero debitis maxime reiciendis beatae adipisci at! Quis dolor voluptatum quod sint exercitationem cumque aut?
                Dolorem adipisci nulla voluptatibus, dignissimos eius aut voluptatum dolor non numquam reiciendis commodi velit ut sed, porro vero cum hic, quas vitae beatae ad nesciunt quo cumque quam. Neque, impedit.
                Optio ut fuga quod unde minima commodi iure eum maxime consectetur, quasi consequuntur facere omnis vero sunt adipisci facilis dolor nesciunt corporis amet dolore aperiam aut! Laboriosam delectus maxime iure.</div>
        </div>
    );
};

export default News;    